Fix 403 client error by enforcing TLS V1.3 (#176)
Since June 12th, 2026 the Tesla API is systematically rejecting requests.

This fix is the result of findings of the teslamate
project (https://github.com/teslamate-org/teslamate/issues/5384).

It seems that tokens generated without TLS v1.3 are not considered valid
for the owner API anymore.

Relevant logs:
  File "/home/jcompost/.local/lib/python3.9/site-packages/teslapy/__init__.py", line 375, in vehicle_list
  f) for v in self.api('PRODUCT_LIST')['response']]
  File "/home/jcompost/.local/lib/python3.9/site-packages/teslapy/__init__.py", line 369, in api
  dpoint['TYPE'], uri, serialize,
  File "/home/jcompost/.local/lib/python3.9/site-packages/teslapy/__init__.py", line 158, in request
  tus()  # Raise HTTPError, if one occurred
  File "/home/jcompost/.local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
  requests.exceptions.HTTPError: 403 Client Error: forbidden, see https://developer.tesla.com/docs/fleet-api for url: https://owner-api.teslamotors.com/api/1/products

Signed-off-by: Jeremy Compostella <jeremy.compostella@gmail.com>
Co-authored-by: Tim Dorssers <39435669+tdorssers@users.noreply.github.com>